name: Wine Ubuntu CI

on:
  schedule:
    - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Compilation
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          cd wine-tkg-xl
          sed -i 's/distro=""/distro="debuntu"/' customization.cfg
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wine-tkg-xl-build
          path: wine-tkg-xl/non-makepkg-builds
